import 'package:flutter/material.dart';
// import 'package:node_flutter_practice/pages/BusService/Bus.dart';
import 'package:node_flutter_practice/pages/BusService/models/buses.dart';
import 'package:node_flutter_practice/pages/BusService/models/category.dart';

const DUMMY_DATA = const [
  Category(id: 'c1', title: 'Royal', color: Colors.deepPurple ),
  Category(id: 'c2', title: 'Bogdad', color: Colors.orange ),
  Category(id: 'c3', title: 'itluf', color: Colors.green ),
  Category(id: 'c4', title: 'BayOfBangla', color: Colors.pinkAccent ),
  Category(id: 'c5', title: 'Tiger', color: Colors.greenAccent ),
  Category(id: 'c6', title: 'BRTC', color: Colors.blue ),
  Category(id: 'c7', title: 'BayOfBangla', color: Colors.pinkAccent ),
  Category(id: 'c8', title: 'Tiger', color: Colors.greenAccent ),
  Category(id: 'c9', title: 'BRTC', color: Colors.blue ),
];

const DUMMY_BUS  = [

  // c1
  Bus(
    id: 'b1',
    categories: [ 'c1', 'c2','c3','c4','c5','c6','c7','c8','c9'],
    title: 'DHK - CTG',
    Affordable: Affordablility.Luxurious,
    NonAc:  Weather.AC,
    imageUrl: 'https://images.unsplash.com/photo-1534359265607-b9cdb5e0a81e?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=321&q=80',
    duration: '2h' ,
    withAc: true,
    isDirect: true,
    isLuxurious: false,
  ),
  Bus(
    id: 'b2',
    categories: [ 'c1'],
    title: 'DHK - COM',
    Affordable: Affordablility.Pricey,
    NonAc:  Weather.NonAc,
    imageUrl: 'https://images.unsplash.com/photo-1562620669-98104534c6cd?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=334&q=80',
    duration: '2h' ,
    withAc: true,
    isDirect: true,
    isLuxurious: false,
  ),
  Bus(
    id: 'b2',
    categories: [ 'c1','c2','c3','c4','c5','c6','c7','c8','c9'],
    title: 'COM - KHULNA',
    Affordable: Affordablility.Affordable,
    NonAc:  Weather.NonAc,
    imageUrl: 'https://images.unsplash.com/photo-1525962898597-a4ae6402826e?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80',
    duration: '2h' ,
    withAc: true,
    isDirect: true,
    isLuxurious: false,
  ),
  Bus(
    id: 'b1',
    categories: [ 'c1'],
    title: 'COM - CTG',
    Affordable: Affordablility.Affordable,
    NonAc:  Weather.NonAc,
    imageUrl: 'https://images.unsplash.com/photo-1525962898597-a4ae6402826e?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80',
    duration: '2h' ,
    withAc: true,
    isDirect: true,
    isLuxurious: false,
  ),
  Bus(
    id: 'b1',
    categories: [ 'c1','c2','c3','c4','c5','c6','c7','c8','c9'],
    title: 'COM - CTG',
    Affordable: Affordablility.Luxurious,
    NonAc:  Weather.AC,
    imageUrl: 'https://images.unsplash.com/photo-1525962898597-a4ae6402826e?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80',
    duration: '2h' ,
    withAc: true,
    isDirect: true,
    isLuxurious: false,
  ),
  Bus(
    id: 'b1',
    categories: [ 'c1'],
    title: 'DHK - SHNDRBN',
    Affordable: Affordablility.Affordable,
    NonAc:  Weather.NonAc,
    imageUrl: 'https://images.unsplash.com/photo-1594767059028-57f64cd78eb1?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=750&q=80',
    duration: '2h' ,
    withAc: true,
    isDirect: true,
    isLuxurious: false,
  ),

  Bus(
    id: 'b1',
    categories: [ 'c1'],
    title: 'DHK - SHNDRBN',
    Affordable: Affordablility.Luxurious,
    NonAc:  Weather.AC,
    imageUrl: 'https://images.unsplash.com/photo-1594767059028-57f64cd78eb1?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=750&q=80',
    duration: '2h' ,
    withAc: true,
    isDirect: true,
    isLuxurious: false,
  ),
  Bus(
    id: 'b2',
    categories: [ 'c1'],
    title: 'DHK - SHNDRBN',
    Affordable: Affordablility.Affordable,
    NonAc:  Weather.AC,
    imageUrl: 'https://images.unsplash.com/photo-1594767059028-57f64cd78eb1?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=750&q=80',
    duration: '2h' ,
    withAc: true,
    isDirect: true,
    isLuxurious: false,
  ),
  Bus(
    id: 'b1',
    categories: [ 'c2'],
    title: 'DHK - SHNDRBN',
    Affordable: Affordablility.Affordable,
    NonAc:  Weather.NonAc,
    imageUrl: 'https://images.unsplash.com/photo-1594767059028-57f64cd78eb1?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=750&q=80',
    duration: '2h' ,
    withAc: true,
    isDirect: true,
    isLuxurious: false,
  ),
  Bus(
    id: 'b1',
    categories: [ 'c7'],
    title: 'DHK - COM',
    Affordable: Affordablility.Pricey,
    NonAc:  Weather.NonAc,
    imageUrl: 'https://images.unsplash.com/photo-1562620669-98104534c6cd?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=334&q=80',
    duration: '2h' ,
    withAc: true,
    isDirect: true,
    isLuxurious: false,
  ),
  Bus(
    id: 'b1',
    categories: [ 'c7'],
    title: 'DHK - COM',
    Affordable: Affordablility.Pricey,
    NonAc:  Weather.NonAc,
    imageUrl: 'https://images.unsplash.com/photo-1562620669-98104534c6cd?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=334&q=80',
    duration: '2h' ,
    withAc: true,
    isDirect: true,
    isLuxurious: false,
  ),
  Bus(
    id: 'b2',
    categories: [ 'c1', 'c5' ],
    title: 'royal title2',
    Affordable: Affordablility.Luxurious,
    NonAc :  Weather.AC,
    imageUrl: 'https://images.unsplash.com/photo-1610480855121-b6541ac27652?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=376&q=80',
    duration: '2.5h' ,
    withAc: false,
    isDirect: true,
    isLuxurious: true,
  ),

  //c2
  Bus(
    id: 'b3',
    categories: [ 'c1', 'c5' ],
    title: 'royal title2 33333',
    Affordable: Affordablility.Affordable,
    NonAc :  Weather.AC,
    imageUrl: 'https://images.unsplash.com/photo-1610538928507-6007cf65197a?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=400&q=80',
    duration: '4h' ,
    withAc: false,
    isDirect: true,
    isLuxurious: true,
  ),
  Bus(
    id: 'b4',
    categories: [ 'c1', 'c5' ],
    title: 'royal title2254251',
    Affordable: Affordablility.Affordable,
    NonAc :  Weather.AC,
    imageUrl: 'https://unsplash.com/photos/Dnjc6ZYGE4s',
    withAc: false,
    isDirect: true,
    isLuxurious: true,
  ),
  Bus(
    id: 'b1',
    categories: [ 'c4' ],
    title: 'royal title3',
    Affordable: Affordablility.Affordable,
    NonAc:  Weather.NonAc,
    imageUrl: 'https://images.unsplash.com/photo-1592143351364-7bf46dd24a68?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=400&q=80',
    withAc: true,
    isDirect: true,
    isLuxurious: true,
  ),
  Bus(
    id: 'b5',
    categories: [ 'c7', 'c8' ],
    title: 'DHK - COM',
    Affordable: Affordablility.Pricey,
    NonAc:  Weather.NonAc,
    imageUrl: 'https://images.unsplash.com/photo-1610488090250-167639ae8f83?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=334&q=80',
    duration: '2h' ,
    withAc: true,
    isDirect: true,
    isLuxurious: false,
  ),
  Bus(
    id: 'b2',
    categories: [ 'c1', 'c5' ],
    title: 'royal title2',
    Affordable: Affordablility.Luxurious,
    NonAc :  Weather.AC,
    imageUrl: 'https://images.unsplash.com/photo-1610480855121-b6541ac27652?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=376&q=80',
    duration: '2.5h' ,
    withAc: false,
    isDirect: true,
    isLuxurious: true,
  ),
  Bus(
    id: 'b3',
    categories: [ 'c1', 'c5' ],
    title: 'royal title2 33333',
    Affordable: Affordablility.Affordable,
    NonAc :  Weather.AC,
    imageUrl: 'https://images.unsplash.com/photo-1610538928507-6007cf65197a?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=400&q=80',
    duration: '4h' ,
    withAc: false,
    isDirect: true,
    isLuxurious: true,
  ),
  Bus(
    id: 'b4',
    categories: [ 'c1', 'c5' ],
    title: 'royal title2254251',
    Affordable: Affordablility.Affordable,
    NonAc :  Weather.AC,
    imageUrl: 'https://unsplash.com/photos/Dnjc6ZYGE4s',
    withAc: false,
    isDirect: true,
    isLuxurious: true,
  ),
  Bus(
    id: 'b1',
    categories: [ 'c4' ],
    title: 'royal title3',
    Affordable: Affordablility.Affordable,
    NonAc:  Weather.NonAc,
    imageUrl: 'https://images.unsplash.com/photo-1592143351364-7bf46dd24a68?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=400&q=80',
    withAc: true,
    isDirect: true,
    isLuxurious: true,
  ),
  //c2
  Bus(
    id: 'b3',
    categories: [ 'c1', 'c5' ],
    title: 'royal title2 33333',
    Affordable: Affordablility.Affordable,
    NonAc :  Weather.AC,
    imageUrl: 'https://images.unsplash.com/photo-1610538928507-6007cf65197a?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=400&q=80',
    duration: '4h' ,
    withAc: false,
    isDirect: true,
    isLuxurious: true,
  ),
  Bus(
    id: 'b4',
    categories: [ 'c1', 'c5' ],
    title: 'royal title2254251',
    Affordable: Affordablility.Affordable,
    NonAc :  Weather.AC,
    imageUrl: 'https://unsplash.com/photos/Dnjc6ZYGE4s',
    withAc: false,
    isDirect: true,
    isLuxurious: true,
  ),
  Bus(
    id: 'b1',
    categories: [ 'c4' ],
    title: 'royal title3',
    Affordable: Affordablility.Affordable,
    NonAc:  Weather.NonAc,
    imageUrl: 'https://images.unsplash.com/photo-1592143351364-7bf46dd24a68?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=400&q=80',
    withAc: true,
    isDirect: true,
    isLuxurious: true,
  ),
  Bus(
    id: 'b1',
    categories: [ 'c7', 'c8' ],
    title: 'DHK - COM',
    Affordable: Affordablility.Pricey,
    NonAc:  Weather.NonAc,
    imageUrl: 'https://images.unsplash.com/photo-1610488090250-167639ae8f83?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=334&q=80',
    duration: '2h' ,
    withAc: true,
    isDirect: true,
    isLuxurious: false,
  ),
  Bus(
    id: 'b2',
    categories: [ 'c1', 'c5' ],
    title: 'royal title2',
    Affordable: Affordablility.Luxurious,
    NonAc :  Weather.AC,
    imageUrl: 'https://images.unsplash.com/photo-1610480855121-b6541ac27652?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=376&q=80',
    duration: '2.5h' ,
    withAc: false,
    isDirect: true,
    isLuxurious: true,
  ),
  Bus(
    id: 'b3',
    categories: [ 'c1', 'c5' ],
    title: 'royal title2 33333',
    Affordable: Affordablility.Affordable,
    NonAc :  Weather.AC,
    imageUrl: 'https://images.unsplash.com/photo-1610538928507-6007cf65197a?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=400&q=80',
    duration: '4h' ,
    withAc: false,
    isDirect: true,
    isLuxurious: true,
  ),
  Bus(
    id: 'b4',
    categories: [ 'c1', 'c5' ],
    title: 'royal title2254251',
    Affordable: Affordablility.Affordable,
    NonAc :  Weather.AC,
    imageUrl: 'https://unsplash.com/photos/Dnjc6ZYGE4s',
    withAc: false,
    isDirect: true,
    isLuxurious: true,
  ),
  Bus(
    id: 'b1',
    categories: [ 'c4' ],
    title: 'royal title3',
    Affordable: Affordablility.Affordable,
    NonAc:  Weather.NonAc,
    imageUrl: 'https://images.unsplash.com/photo-1592143351364-7bf46dd24a68?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=400&q=80',
    withAc: true,
    isDirect: true,
    isLuxurious: true,
  ),
  //c2
  Bus(
    id: 'b3',
    categories: [ 'c1', 'c5' ],
    title: 'royal title2 33333',
    Affordable: Affordablility.Affordable,
    NonAc :  Weather.AC,
    imageUrl: 'https://images.unsplash.com/photo-1610538928507-6007cf65197a?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=400&q=80',
    duration: '4h' ,
    withAc: false,
    isDirect: true,
    isLuxurious: true,
  ),
  Bus(
    id: 'b4',
    categories: [ 'c1', 'c5' ],
    title: 'royal title2254251',
    Affordable: Affordablility.Affordable,
    NonAc :  Weather.AC,
    imageUrl: 'https://unsplash.com/photos/Dnjc6ZYGE4s',
    withAc: false,
    isDirect: true,
    isLuxurious: true,
  ),
  Bus(
    id: 'b1',
    categories: [ 'c4' ],
    title: 'royal title3',
    Affordable: Affordablility.Affordable,
    NonAc:  Weather.NonAc,
    imageUrl: 'https://images.unsplash.com/photo-1592143351364-7bf46dd24a68?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=400&q=80',
    withAc: true,
    isDirect: true,
    isLuxurious: true,
  ),
  Bus(
    id: 'b1',
    categories: [ 'c7', 'c8' ],
    title: 'DHK - COM',
    Affordable: Affordablility.Pricey,
    NonAc:  Weather.NonAc,
    imageUrl: 'https://images.unsplash.com/photo-1610488090250-167639ae8f83?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=334&q=80',
    duration: '2h' ,
    withAc: true,
    isDirect: true,
    isLuxurious: false,
  ),
  Bus(
    id: 'b2',
    categories: [ 'c1', 'c5' ],
    title: 'royal title2',
    Affordable: Affordablility.Luxurious,
    NonAc :  Weather.AC,
    imageUrl: 'https://images.unsplash.com/photo-1610480855121-b6541ac27652?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=376&q=80',
    duration: '2.5h' ,
    withAc: false,
    isDirect: true,
    isLuxurious: true,
  ),
  Bus(
    id: 'b3',
    categories: [ 'c1', 'c5' ],
    title: 'royal title2 33333',
    Affordable: Affordablility.Affordable,
    NonAc :  Weather.AC,
    imageUrl: 'https://images.unsplash.com/photo-1610538928507-6007cf65197a?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=400&q=80',
    duration: '4h' ,
    withAc: false,
    isDirect: true,
    isLuxurious: true,
  ),
  Bus(
    id: 'b4',
    categories: [ 'c1', 'c5' ],
    title: 'royal title2254251',
    Affordable: Affordablility.Affordable,
    NonAc :  Weather.AC,
    imageUrl: 'https://unsplash.com/photos/Dnjc6ZYGE4s',
    withAc: false,
    isDirect: true,
    isLuxurious: true,
  ),
  Bus(
    id: 'b1',
    categories: [ 'c4' ],
    title: 'royal title3',
    Affordable: Affordablility.Affordable,
    NonAc:  Weather.NonAc,
    imageUrl: 'https://images.unsplash.com/photo-1592143351364-7bf46dd24a68?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=400&q=80',
    withAc: true,
    isDirect: true,
    isLuxurious: true,
  ),
  Bus(
    id: 'b1',
    categories: [ 'c7', 'c8' ],
    title: 'DHK - COM',
    Affordable: Affordablility.Pricey,
    NonAc:  Weather.NonAc,
    imageUrl: 'https://images.unsplash.com/photo-1610488090250-167639ae8f83?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=334&q=80',
    duration: '2h' ,
    withAc: true,
    isDirect: true,
    isLuxurious: false,
  ),
  Bus(
    id: 'b2',
    categories: [ 'c1', 'c5' ],
    title: 'royal title2',
    Affordable: Affordablility.Luxurious,
    NonAc :  Weather.AC,
    imageUrl: 'https://images.unsplash.com/photo-1610480855121-b6541ac27652?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=376&q=80',
    duration: '2.5h' ,
    withAc: false,
    isDirect: true,
    isLuxurious: true,
  ),
  Bus(
    id: 'b3',
    categories: [ 'c1', 'c5' ],
    title: 'royal title2 33333',
    Affordable: Affordablility.Affordable,
    NonAc :  Weather.AC,
    imageUrl: 'https://images.unsplash.com/photo-1610538928507-6007cf65197a?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=400&q=80',
    duration: '4h' ,
    withAc: false,
    isDirect: true,
    isLuxurious: true,
  ),
  Bus(
    id: 'b4',
    categories: [ 'c1', 'c5' ],
    title: 'royal title2254251',
    Affordable: Affordablility.Affordable,
    NonAc :  Weather.AC,
    imageUrl: 'https://unsplash.com/photos/Dnjc6ZYGE4s',
    withAc: false,
    isDirect: true,
    isLuxurious: true,
  ),
  Bus(
    id: 'b1',
    categories: [ 'c4' ],
    title: 'royal title3',
    Affordable: Affordablility.Affordable,
    NonAc:  Weather.NonAc,
    imageUrl: 'https://images.unsplash.com/photo-1592143351364-7bf46dd24a68?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=400&q=80',
    withAc: true,
    isDirect: true,
    isLuxurious: true,
  ),

];