import 'package:flutter/material.dart';
// import 'package:node_flutter_practice/pages/BusService/Bus.dart';
import 'package:node_flutter_practice/pages/BusService/models/category.dart';
import 'package:node_flutter_practice/pages/HotelService/models/hotel.dart';

const DUMMY_DATA = const [
  Category(id: 'c1', title: 'hotels 1', color: Colors.deepPurple ),
  Category(id: 'c2', title: 'Bogdad', color: Colors.deepPurple ),
  Category(id: 'c3', title: 'itluf', color: Colors.deepPurple ),
  Category(id: 'c4', title: 'BayOfBangla', color: Colors.deepPurple ),
  Category(id: 'c5', title: 'Tiger', color: Colors.deepPurple ),
  Category(id: 'c6', title: 'BRTC', color: Colors.deepPurple ),
  Category(id: 'c7', title: 'BayOfBangla', color: Colors.deepPurple ),
  Category(id: 'c8', title: 'Tiger', color: Colors.deepPurple ),
  Category(id: 'c9', title: 'BRTC', color: Colors.deepPurple ),
];

const DUMMY_Hotel  = [

  // c1
  Hotel(
    id: 'b1',
    categories: [ 'c1', 'c2','c3','c4','c5','c6','c7','c8','c9'],
    title: 'DHK - CTG',
    Affordable: Affordablility.Luxurious,
    NonAc:  Weather.AC,
    imageUrl: 'https://images.unsplash.com/photo-1534359265607-b9cdb5e0a81e?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=321&q=80',
    duration: '2h' ,
    withAc: true,
    isDirect: true,
    isLuxurious: false,
  ),
  Hotel(
    id: 'b2',
    categories: [ 'c1'],
    title: 'DHK - COM',
    Affordable: Affordablility.Pricey,
    NonAc:  Weather.NonAc,
    imageUrl: 'https://images.unsplash.com/photo-1562620669-98104534c6cd?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=334&q=80',
    duration: '2h' ,
    withAc: true,
    isDirect: true,
    isLuxurious: false,
  ),
  Hotel(
    id: 'b2',
    categories: [ 'c1','c2','c3','c4','c5','c6','c7','c8','c9'],
    title: 'COM - KHULNA',
    Affordable: Affordablility.Affordable,
    NonAc:  Weather.NonAc,
    imageUrl: 'https://images.unsplash.com/photo-1525962898597-a4ae6402826e?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80',
    duration: '2h' ,
    withAc: true,
    isDirect: true,
    isLuxurious: false,
  ),
  Hotel(
    id: 'b1',
    categories: [ 'c1'],
    title: 'COM - CTG',
    Affordable: Affordablility.Affordable,
    NonAc:  Weather.NonAc,
    imageUrl: 'https://images.unsplash.com/photo-1525962898597-a4ae6402826e?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80',
    duration: '2h' ,
    withAc: true,
    isDirect: true,
    isLuxurious: false,
  ),
  Hotel(
    id: 'b1',
    categories: [ 'c1','c2','c3','c4','c5','c6','c7','c8','c9'],
    title: 'COM - CTG',
    Affordable: Affordablility.Luxurious,
    NonAc:  Weather.AC,
    imageUrl: 'https://images.unsplash.com/photo-1525962898597-a4ae6402826e?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80',
    duration: '2h' ,
    withAc: true,
    isDirect: true,
    isLuxurious: false,
  ),
  Hotel(
    id: 'b1',
    categories: [ 'c1'],
    title: 'DHK - SHNDRBN',
    Affordable: Affordablility.Affordable,
    NonAc:  Weather.NonAc,
    imageUrl: 'https://images.unsplash.com/photo-1594767059028-57f64cd78eb1?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=750&q=80',
    duration: '2h' ,
    withAc: true,
    isDirect: true,
    isLuxurious: false,
  ),

  Hotel(
    id: 'b1',
    categories: [ 'c1'],
    title: 'DHK - SHNDRBN',
    Affordable: Affordablility.Luxurious,
    NonAc:  Weather.AC,
    imageUrl: 'https://images.unsplash.com/photo-1594767059028-57f64cd78eb1?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=750&q=80',
    duration: '2h' ,
    withAc: true,
    isDirect: true,
    isLuxurious: false,
  ),
  Hotel(
    id: 'b2',
    categories: [ 'c1'],
    title: 'DHK - SHNDRBN',
    Affordable: Affordablility.Affordable,
    NonAc:  Weather.AC,
    imageUrl: 'https://images.unsplash.com/photo-1594767059028-57f64cd78eb1?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=750&q=80',
    duration: '2h' ,
    withAc: true,
    isDirect: true,
    isLuxurious: false,
  ),
  Hotel(
    id: 'b1',
    categories: [ 'c2'],
    title: 'DHK - SHNDRBN',
    Affordable: Affordablility.Affordable,
    NonAc:  Weather.NonAc,
    imageUrl: 'https://images.unsplash.com/photo-1594767059028-57f64cd78eb1?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=750&q=80',
    duration: '2h' ,
    withAc: true,
    isDirect: true,
    isLuxurious: false,
  ),
];